### ISSUE TITLE
Configure UserAgent not used

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny4OTRS-EnhancedProxySupport#2]
The configure UserAgent  is not used when fetching RSS feeds.

**Comment by dennybresch** [comment]
Is this error still present?
@rkaldung

**Comment by rkaldung** [comment]
I'll check today

**Comment by rkaldung** [comment]
Yes, UserAgent is not used

**Comment by dennybresch** [comment]
Typo in Code:

`WebUserAgentString::UserAgentString` != `WebUserAgent::UserAgent`

https://github.com/znuny/Znuny4OTRS-EnhancedProxySupport/commit/8760556be37adf845bc34994af0b2c92efd1ad26

**Comment by dennybresch** [comment]
Fixed typo in master, master5, master4:

https://github.com/znuny/Znuny4OTRS-EnhancedProxySupport/commit/33ee0358642d55984917d957c630c49e12e74bb2
